#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the bitcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x34,0x46,0xef,0x2c,0x26,0x2d,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x34,0x46,0xef,0x2c,0x4d,0x3d,
};

static const uint8_t chainparams_seed_testnet4[] = {
    0x01,0x04,0x34,0x46,0xef,0x2c,0xc2,0x6d,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
